version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "80:1337"
    volumes:
      - ./:/rta
    command: bash -c "npm install && npm start"
